apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-go
  template:
    metadata:
      labels:
        app: server-go
        tier: backend
        track: stable
    spec:
      containers:
        - name: server-go
          image: "server-go:1"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: backend-port
              containerPort: 5001
