version: "3.8"
services:
  watchtower:
    image: v2tec/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: watchtower docker pull ghcr.io/zsbrybnik/zsbwebsite ghcr.io/zsbrybnik/zsbservergo ghcr.io/zsbrybnik/zsbcdnrust mysql phpmyadmin/phpmyadmin redis fauria/vsftpd --interval 30
    restart: unless-stopped
  zsbwebsite:
    image: ghcr.io/zsbrybnik/zsbwebsite:latest
    container_name: zsbwebsite
    ports:
      - "5000:5000"
    networks:
      - fullstack
    restart: on-failure
    environment:
      - REACT_APP_CDN_URL=${REACT_APP_CDN_URL}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - zsbservergo
      - zsbcdnrust
      #  - zsbcdngo
  zsbservergo:
    container_name: zsbserver
    image: ghcr.io/zsbrybnik/zsbservergo:latest
    ports:
      - "5001:5001"
    depends_on:
      - zsbdatabase
      - zsbredis
    networks:
      - fullstack
    restart: on-failure
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - MAIN_APP_URL=${MAIN_APP_URL}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SIGNATURE=${JWT_SIGNATURE}
  zsbdatabase:
    container_name: zsbdatabase
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - fullstack
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: on-failure
  zsbphpmyadmin:
    container_name: zsbphpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "4000:80"
    networks:
      - fullstack
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      PMA_HOST: "host.docker.internal"
    restart: on-failure
    depends_on:
      - zsbdatabase
  zsbredis:
    container_name: zsbredis
    image: redis:latest
    restart: on-failure
    networks:
      - fullstack
    expose:
      - "6379"
    ports:
      - "6379:6379"
  # zsbcdngo:
  #  container_name: zsbcdngo
  #  build: ./cdn-go
  #  ports:
  #    - "5002:5002"
  #  networks:
  #    - fullstack
  #  restart: on-failure
  #  depends_on:
  #    - zsbftp
  zsbcdnrust:
    container_name: zsbcdnrust
    image: ghcr.io/zsbrybnik/zsbcdnrust:latest
    ports:
      - "5002:5002"
    networks:
      - fullstack
    restart: on-failure
    depends_on:
      - zsbftp
    volumes:
      - ./public:/public
  zsbftp:
    container_name: zsbftp
    image: fauria/vsftpd:latest
    environment:
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    networks:
      - fullstack
    volumes:
      - ./public:/home/vsftpd/admin
    restart: on-failure

networks:
  fullstack:
    driver: bridge
